services:
  - type: web
    name: tripcounter
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --log-level debug --capture-output --enable-stdio-inheritance"
